// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MVPv5.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MVPv5.API.Migrations;

[DbContext(typeof(MVPv5DbContext))]
partial class MVPv5DatabaseModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("MVPv5.Domain.Entities.UserEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<char>("AccessRule")
                    .HasColumnType("character(1)");

                b.Property<string>("Login")
                    .HasColumnType("text");

                b.Property<string>("Nickname")
                    .HasColumnType("text");

                b.Property<string>("Password")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Users");
            });
#pragma warning restore 612, 618
    }
}
