@MVPv5_HostAddress = http://localhost:5123
# TODO - можно ли как-то отвязать от прямого написания адреса?

GET {{MVPv5_HostAddress}}/User/Get/3
Accept: application/json


###

POST {{MVPv5_HostAddress}}/User/create/
Content-Type: application/json
{
  "Nickname": "Билли Херрингтон",
  "Login" : "dungeonmaster",
  "Password": "14881488",
  "PasswordConfirm": "14881488"
}

###