@MVPv5_HostAddress = http://localhost:5123
# TODO - можно ли как-то отвязать от прямого написания адреса?

# GET {{MVPv5_HostAddress}}/weatherforecast/
# Accept: application/json

###

POST {{MVPv5_HostAddress}}/User/create/
Content-Type: application/json
{
  "Nickname": "big ass dick",
  "Login" : "looooooooooogin",
  "Password": "1234567",
  "PasswordConfirm": "1"
}

###

POST {{MVPv5_HostAddress}}/User/create/
Content-Type: application/json
{
  "Nickname": "ass we can",
  "Login" : "boynextdoor",
  "Password": "123",
  "PasswordConfirm": "123"
}

###

POST {{MVPv5_HostAddress}}/User/create/
Content-Type: application/json
{
  "Nickname": "Билли Херрингтон",
  "Login" : "dungeonmaster",
  "Password": "14881488",
  "PasswordConfirm": "14881488"
}

###